Added berzerk 20, 30, and berzerk job skill quest items
BenjixD/MapleSolaxiaV2 pull request #105
Opened 2020-01-26 03:14 UTC by allenaerostar

Added berzerk 20, 30, and berzerk job skill quest items

2020-01-26 19:12 UTC, BenjixD requested changes
Please add comments to the insert  statements in similar style to previously submitted sql files.

2020-01-27 06:35 UTC, BenjixD approved these changes

2020-01-27 06:55 UTC, tzwang1 requested changes
Please add "USE dietstory" to the top of the scripts.

2020-01-27 06:55 UTC, tzwang1 approved these changes

2020-01-27 11:57 UTC, merged