Fix/snipe quest
BenjixD/MapleSolaxiaV2 pull request #110
Opened 2020-01-27 20:12 UTC by BenjixD

Calling `getEligibleParty` fixes`nullPointerException` when calling `em.startInstance`

2020-01-27 20:43 UTC, nansonzheng requested changes
Fix the typo and it should be ok

2020-01-27 20:43 UTC, nansonzheng commented on scripts/npc/1061012.js
> +	1
Stray 1

2020-01-27 21:00 UTC, BenjixD commented on scripts/npc/1061012.js
> +	1
nice

2020-01-28 00:40 UTC, nansonzheng approved these changes

2020-01-28 01:06 UTC, merged